//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace OnlineExamPlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourseData()
        {
            this.CourseTransactions = new HashSet<CourseTransaction>();
            this.ExamHeaders = new HashSet<ExamHeader>();
            this.QuestionDatas = new HashSet<QuestionData>();
            this.StudentGroups = new HashSet<StudentGroup>();
            this.ExaminationProcesses = new HashSet<ExaminationProcess>();
        }
    
        public long CourseDataID { get; set; }
        public Nullable<System.Guid> CourseDataGUID { get; set; }

        [Display(Name = "Course Code")]
        [Required]
        public string CourseCode { get; set; }



        [Display(Name = "Course Name")]
        [Required]
        public string CourseName { get; set; }



        public Nullable<bool> IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }


        [Display(Name = "Department")]
        [Required]
        public Nullable<int> DepartmentId { get; set; }


        [Display(Name = "Grade Year")]
        [Required]
        public Nullable<int> GradeYearID { get; set; }



        [Display(Name = "Semester")]
        [Required]
        public Nullable<int> SemesterId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseTransaction> CourseTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamHeader> ExamHeaders { get; set; }
        public virtual Department Department { get; set; }
        public virtual GradeYear GradeYear { get; set; }
        public virtual Semester Semester { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionData> QuestionDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentGroup> StudentGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExaminationProcess> ExaminationProcesses { get; set; }
    }
}
