//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExamPlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseTransaction
    {
        public long CourseTransactionID { get; set; }
        public Nullable<System.Guid> CourseTransactionGUID { get; set; }
        public Nullable<long> CourseDataID { get; set; }
        public Nullable<long> StudentID { get; set; }
        public Nullable<long> ExaminerID { get; set; }
        public long NumberOfStudents { get; set; }
        public System.DateTime AcademicYear { get; set; }
        public string StudentStatus { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual CourseData CourseData { get; set; }
        public virtual ExaminerData ExaminerData { get; set; }
        public virtual StudentData StudentData { get; set; }
    }
}
