//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExamPlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExaminationProcess
    {
        public long ExaminationProcessID { get; set; }
        public Nullable<System.Guid> ExaminationProcessGUID { get; set; }
        public Nullable<long> ExaminerID { get; set; }
        public Nullable<long> StudentID { get; set; }
        public Nullable<long> ExamID { get; set; }
        public decimal StudentResult { get; set; }
        public Nullable<long> CourseDataID { get; set; }
        public Nullable<bool> IsPublished { get; set; }
    
        public virtual ExamHeader ExamHeader { get; set; }
        public virtual ExaminerData ExaminerData { get; set; }
        public virtual StudentData StudentData { get; set; }
        public virtual CourseData CourseData { get; set; }
    }
}
