//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExamPlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamDetail
    {
        public long ExamDetailsID { get; set; }
        public Nullable<System.Guid> ExamDetailsGUID { get; set; }
        public Nullable<long> ExamID { get; set; }
        public Nullable<long> QuestionID { get; set; }
        public long NumberOfQuestions { get; set; }
        public Nullable<long> StudentGroupID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ExamHeader ExamHeader { get; set; }
        public virtual StudentGroup StudentGroup { get; set; }
        public virtual QuestionData QuestionData { get; set; }
    }
}
