//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExamPlatform.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnXamsEntities : DbContext
    {
        public OnXamsEntities()
            : base("name=OnXamsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminData> AdminDatas { get; set; }
        public virtual DbSet<CourseData> CourseDatas { get; set; }
        public virtual DbSet<CourseTransaction> CourseTransactions { get; set; }
        public virtual DbSet<ExamDetail> ExamDetails { get; set; }
        public virtual DbSet<ExamHeader> ExamHeaders { get; set; }
        public virtual DbSet<ExaminationProcess> ExaminationProcesses { get; set; }
        public virtual DbSet<ExaminerData> ExaminerDatas { get; set; }
        public virtual DbSet<ExaminerPermission> ExaminerPermissions { get; set; }
        public virtual DbSet<OptionsOfMcqQuestion> OptionsOfMcqQuestions { get; set; }
        public virtual DbSet<PermissionData> PermissionDatas { get; set; }
        public virtual DbSet<ProctorData> ProctorDatas { get; set; }
        public virtual DbSet<ProctorPermission> ProctorPermissions { get; set; }
        public virtual DbSet<QuestionData> QuestionDatas { get; set; }
        public virtual DbSet<ReportDetail> ReportDetails { get; set; }
        public virtual DbSet<ReportHeader> ReportHeaders { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RolesMappingUser> RolesMappingUsers { get; set; }
        public virtual DbSet<StudentAnswersQuestionInExam> StudentAnswersQuestionInExams { get; set; }
        public virtual DbSet<StudentData> StudentDatas { get; set; }
        public virtual DbSet<StudentPermission> StudentPermissions { get; set; }
        public virtual DbSet<UserAuthentication> UserAuthentications { get; set; }
        public virtual DbSet<LogData> LogDatas { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<GradeYear> GradeYears { get; set; }
        public virtual DbSet<Semester> Semesters { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<QuestionType> QuestionTypes { get; set; }
        public virtual DbSet<SubCategory> SubCategories { get; set; }
        public virtual DbSet<QuestionWeight> QuestionWeights { get; set; }
        public virtual DbSet<StudentGroup> StudentGroups { get; set; }
        public virtual DbSet<StudentMapToGroup> StudentMapToGroups { get; set; }
    }
}
