//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExamPlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionsOfMcqQuestion
    {
        public long OptionsOfMcqQuestionsID { get; set; }
        public long QuestionDataID { get; set; }
        public Nullable<System.Guid> OptionsOfMcqQuestionsGUID { get; set; }
        public string OptionsImage { get; set; }
        public long OptionNumber { get; set; }
        public string OptionDescription { get; set; }
        public Nullable<bool> RightOrNot { get; set; }
        public Nullable<long> MinusDegree { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string FirstOption { get; set; }
        public string SecondOption { get; set; }
        public string ThirdOption { get; set; }
        public string FourthOption { get; set; }
    
        public virtual QuestionData QuestionData { get; set; }
    }
}
