//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExamPlatform.Models
{
    using System;
    using System.Collections.Generic;
    using  System.ComponentModel.DataAnnotations;
    public partial class QuestionData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuestionData()
        {
            this.OptionsOfMcqQuestions = new HashSet<OptionsOfMcqQuestion>();
            this.StudentAnswersQuestionInExams = new HashSet<StudentAnswersQuestionInExam>();
            this.ExamDetails = new HashSet<ExamDetail>();
        }
    
        public long QuestionDataID { get; set; }
        public Nullable<System.Guid> QuestionDataGUID { get; set; }
        public string QuestionImage { get; set; }
        [Required]
        [Display(Name = "Question Description")]
        public string QuestionDescription { get; set; }

        [Required]
        [Display(Name = "Question Answer")]
        public string QuestionAnswer { get; set; }


        [Range(typeof(TimeSpan), "00:00:00", "00:59:59")]
        [DataType(DataType.Time)]
        [DisplayFormat(DataFormatString = "{0:hh:mm:ss}", ApplyFormatInEditMode = true)]
        [Display(Name = "Answer time")]
        [Required]
        public System.TimeSpan AnswerTime { get; set; }

        [Display(Name = "Question Source")]
        public string QuestionSource { get; set; }
        public Nullable<long> ExaminerID { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedDate { get; set; }
        public string IpAdress { get; set; }
        public Nullable<long> CourseDataId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> QuestionTypeId { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
        public Nullable<int> QuestionWeightId { get; set; }
        public Nullable<bool> IsQuestionChecked { get; set; }
        public bool IsChecked { get; set; }
      
        public int? SelectedAnswer { get; set; }
        public string StudentAnswerWrite { get; set; }



        public virtual ExaminerData ExaminerData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OptionsOfMcqQuestion> OptionsOfMcqQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentAnswersQuestionInExam> StudentAnswersQuestionInExams { get; set; }
        public virtual CourseData CourseData { get; set; }
        public virtual Category Category { get; set; }
        public virtual QuestionType QuestionType { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual QuestionWeight QuestionWeight { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamDetail> ExamDetails { get; set; }
    }
}
