//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExamPlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportDetail
    {
        public long ReportDetalisID { get; set; }
        public Nullable<System.Guid> ReportDetalisGUID { get; set; }
        public Nullable<long> ReportHeaderID { get; set; }
        public Nullable<long> StudentID { get; set; }
        public string ReportDescription { get; set; }
    
        public virtual ReportHeader ReportHeader { get; set; }
        public virtual StudentData StudentData { get; set; }
    }
}
