//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExamPlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolesMappingUser
    {
        public long Id { get; set; }
        public Nullable<long> RolesId { get; set; }
        public Nullable<long> UserAuthenticationId { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual UserAuthentication UserAuthentication { get; set; }
    }
}
