//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExamPlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentMapToGroup
    {
        public long StudentMapToGroupId { get; set; }
        public Nullable<long> StudentGroupID { get; set; }
        public Nullable<long> StudentID { get; set; }
    
        public virtual StudentData StudentData { get; set; }
        public virtual StudentGroup StudentGroup { get; set; }
    }
}
