//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExamPlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentGroup()
        {
            this.StudentMapToGroups = new HashSet<StudentMapToGroup>();
            this.ExamDetails = new HashSet<ExamDetail>();
        }
    
        public long StudentGroupID { get; set; }
        public Nullable<System.Guid> StudentGroupGuid { get; set; }
        public string GroupName { get; set; }
        public Nullable<long> CourseDataId { get; set; }
        public Nullable<long> ExaminerId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsGroupChecked { get; set; }
        public bool IsChecked { get; set; }
        public virtual CourseData CourseData { get; set; }
        public virtual ExaminerData ExaminerData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentMapToGroup> StudentMapToGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamDetail> ExamDetails { get; set; }
    }
}
