//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExamPlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentPermission
    {
        public long StudentPermissionID { get; set; }
        public Nullable<System.Guid> StudentPermissionGUID { get; set; }
        public Nullable<long> StudentID { get; set; }
        public Nullable<long> PermissionID { get; set; }
        public Nullable<long> ExaminerID { get; set; }
    
        public virtual ExaminerData ExaminerData { get; set; }
        public virtual PermissionData PermissionData { get; set; }
        public virtual StudentData StudentData { get; set; }
    }
}
