//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExamPlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAnswersQuestionInExam
    {
        public long StudentAnswersQuestionInExamID { get; set; }
        public Nullable<System.Guid> StudentAnswersQuestionInExamGUID { get; set; }
        public Nullable<long> StudentID { get; set; }
        public Nullable<long> QuestionID { get; set; }
        public Nullable<long> ExamID { get; set; }
        public string StudentAnswer { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ExamHeader ExamHeader { get; set; }
        public virtual QuestionData QuestionData { get; set; }
        public virtual StudentData StudentData { get; set; }
    }
}
