//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExamPlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAuthentication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserAuthentication()
        {
            this.RolesMappingUsers = new HashSet<RolesMappingUser>();
        }
    
        public long UserAuthenticationId { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<long> AdminId { get; set; }
        public Nullable<long> ProctorId { get; set; }
        public Nullable<long> ExaminerId { get; set; }
        public Nullable<long> StudentID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolesMappingUser> RolesMappingUsers { get; set; }
        public virtual AdminData AdminData { get; set; }
        public virtual ExaminerData ExaminerData { get; set; }
        public virtual ProctorData ProctorData { get; set; }
        public virtual StudentData StudentData { get; set; }
    }
}
